# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"\x1e\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\" \n\x0cMovieRequest\x12\x10\n\x08movie_id\x18\x01 \x01(\x05\"C\n\x0cUserResponse\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x11\n\tis_active\x18\x03 \x01(\x08\"\x8b\x02\n\x05Movie\x12\x10\n\x08movie_id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x14\n\x0crelease_year\x18\x03 \x01(\x05\x12\x10\n\x08universe\x18\x04 \x01(\t\x12\x10\n\x08\x64irector\x18\x05 \x01(\t\x12\x14\n\x0c\x64uration_min\x18\x06 \x01(\x05\x12\x0e\n\x06rating\x18\x07 \x01(\x02\x12\x12\n\nbox_office\x18\x08 \x01(\x03\x12\x13\n\x0b\x64\x65scription\x18\t \x01(\t\x12\x18\n\x04\x63\x61st\x18\n \x03(\x0b\x32\n.user.Cast\x12\x1f\n\x08villains\x18\x0b \x03(\x0b\x32\r.user.Villain\x12\x1d\n\x07reviews\x18\x0c \x03(\x0b\x32\x0c.user.Review\"E\n\x04\x43\x61st\x12\x12\n\nactor_name\x18\x01 \x01(\t\x12\x16\n\x0e\x63haracter_name\x18\x02 \x01(\t\x12\x11\n\trole_type\x18\x03 \x01(\t\"&\n\x07Villain\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x61\x63tor\x18\x02 \x01(\t\"\'\n\x06Review\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x32l\n\x0bUserService\x12\x30\n\x07GetUser\x12\x11.user.UserRequest\x1a\x12.user.UserResponse\x12+\n\x08GetMovie\x12\x12.user.MovieRequest\x1a\x0b.user.Movieb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=20
  _globals['_USERREQUEST']._serialized_end=50
  _globals['_MOVIEREQUEST']._serialized_start=52
  _globals['_MOVIEREQUEST']._serialized_end=84
  _globals['_USERRESPONSE']._serialized_start=86
  _globals['_USERRESPONSE']._serialized_end=153
  _globals['_MOVIE']._serialized_start=156
  _globals['_MOVIE']._serialized_end=423
  _globals['_CAST']._serialized_start=425
  _globals['_CAST']._serialized_end=494
  _globals['_VILLAIN']._serialized_start=496
  _globals['_VILLAIN']._serialized_end=534
  _globals['_REVIEW']._serialized_start=536
  _globals['_REVIEW']._serialized_end=575
  _globals['_USERSERVICE']._serialized_start=577
  _globals['_USERSERVICE']._serialized_end=685
# @@protoc_insertion_point(module_scope)
